import Image from 'next/image';
import React from 'react';
import Head from 'next/head';
import Button, { BUTTON_STYLES } from '@/src/components/Button';
import { useState } from 'react';
import { ArrowUpRightIcon } from '@heroicons/react/24/solid';

const About = () => {
	const foreground = '/images/foreground.png';
	const background = '/images/background.png';
	const arrow = '/images/arrow.svg';
	const [over, setOver] = useState(false);
	return (
		<>
			<Head>
				<title>Yoon Kim | Front End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/favicon.ico" />
			</Head>
			<div className="flex md:flex-row flex-col items-center justify-center py-10">
				<div className="md:w-1/2 flex flex-col gap-5 px-3">
					<h2 className="font-bold tracking-tight text-4xl text-yellow">
						Annyeonghaseyo! 👋
					</h2>
					<div className="text-black dark:text-lightgray text-md">
						<p className="pb-3">
							I’m Yoon (a.k.a.{' '}
							<a
								href="https://www.instagram.com/yoonthecoder"
								target="_blank"
								rel="noreferrer"
								className="text-yellow underline hover:opacity-70"
							>
								yoonthecoder
							</a>
							), a frontend developer who is originally from Korea, but
							currently based in Vancouver, BC. While I initially started out on
							a path in Education, I quickly discovered that my true passions
							lay in the world of tech. So, I taught myself to code and now
							I&apos;m living my dream as a developer! With a keen interest in
							both design and coding, I love getting creative with my work and
							always strive to create websites and applications that are not
							only functional, but also visually stunning.
						</p>
						<p className="pb-3">
							I also love to share my knowledge and experiences with others in
							the developer community. I recently started to create informative
							content on various platforms, so that other developers can learn
							from my tips and tricks and stay motivated with some inspirational
							quotes.
						</p>{' '}
						<p>
							When I&apos;m not glued to my laptop, you can catch me on the
							mountains hitting the slopes and soaking up some nature. It&apos;s
							my way of recharging my batteries!
						</p>{' '}
					</div>
					<div className="flex gap-3">
						<Button
							style={BUTTON_STYLES.UNDERLINE}
							text={
								<div className="flex items-center">
									<div className="mr-1">Resume</div>{' '}
									<ArrowUpRightIcon className="h-4 w-4" />
								</div>
							}
							buttonOnClick={() => (window.open('/Resume_Yoon.pdf'), '_blank')}
						/>
						<Button
							style={BUTTON_STYLES.UNDERLINE}
							text={
								<div className="flex items-center">
									<div className="mr-1">Email me</div>{' '}
									<ArrowUpRightIcon className="h-4 w-4" />
								</div>
							}
							buttonOnClick={() =>
								(window.location.href = 'mailto:imyoonkim@gmail.com')
							}
						/>
					</div>
				</div>
				<div className="md:w-1/2 flex flex-col items-center justify-center">
					<Image
						src={over ? background : foreground}
						width={350}
						height={400}
						alt="headshot"
						className="cursor-pointer"
						onMouseOver={() => setOver(true)}
						onMouseOut={() => setOver(false)}
					/>
					<div className="flex">
						{' '}
						<div className="text-yellow mt-10 mr-2">
							{over ? 'thanks for coming by 💛' : 'hover over me!'}
						</div>
						<Image src={arrow} width={60} height={50} alt="arrow" />
					</div>
				</div>
			</div>
		</>
	);
};

export default About;
