import Image from 'next/image';
import React from 'react';
import Head from 'next/head';
import Button, { BUTTON_STYLES } from '@/src/components/Button';
import { useState } from 'react';
import { ArrowUpRightIcon } from '@heroicons/react/24/solid';

const About = () => {
	const foreground = '/images/foreground.png';
	const background = '/images/background.png';
	const arrow = '/images/arrow.svg';
	const [over, setOver] = useState(false);
	return (
		<>
			<Head>
				<title>Yoon Kim | Front End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/favicon.ico" />
			</Head>
			<div className="flex md:flex-row flex-col items-center justify-center py-10 w-full gap-10">
				<div className="md:w-1/2 flex flex-col gap-5 px-3">
					<h2 className="font-bold tracking-tight text-4xl text-yellow">
						Hi there 👋
					</h2>
					<div className="text-black dark:text-lightgray text-md">
						<p className="pb-3">
							I’m Yoon (a.k.a.{' '}
							<a
								href="https://yoonthecoder.hashnode.dev/"
								target="_blank"
								rel="noreferrer"
								className="text-yellow underline hover:opacity-70"
							>
								yoonthecoder
							</a>
							), a frontend developer based in Vancouver, BC. I’m passionate
							about building websites and apps that not only work seamlessly but
							also look amazing. I love combining design and code to create
							things that people genuinely enjoy using. For me, being a
							developer is about more than just writing code - it&apos;s about
							solving problems and creating solutions that make an impact.
							I&apos;m always working to become a well-rounded engineer who can
							think beyond the technical side and contribute real business value
							to every project I work on.
						</p>
						<p className="pb-3">
							I&apos;m also big on giving back to the developer community.
							Whether it&apos;s mentoring junior developers or sharing tips,
							tricks, and inspiration online, I love helping others grow and
							succeed in their coding journey.
						</p>
						<p>
							When I&apos;m not at my desk, you&apos;ll probably find me
							spending time with my pup, hitting the slopes, or exploring the
							mountains and lakes around Vancouver. Being outdoors is my way of
							recharging and staying inspired!
						</p>
					</div>
					<div className="flex gap-3">
						<Button
							style={BUTTON_STYLES.UNDERLINE}
							text={
								<div className="flex items-center">
									<div className="mr-1">Resume</div>{' '}
									<ArrowUpRightIcon className="h-4 w-4" />
								</div>
							}
							buttonOnClick={() => (window.open('/Resume-YKim.pdf'), '_blank')}
						/>
						<Button
							style={BUTTON_STYLES.UNDERLINE}
							text={
								<div className="flex items-center">
									<div className="mr-1">Email me</div>{' '}
									<ArrowUpRightIcon className="h-4 w-4" />
								</div>
							}
							buttonOnClick={() =>
								(window.location.href = 'mailto:imyoonkim@gmail.com')
							}
						/>
					</div>
				</div>
				<div className="md:w-1/2 flex justify-center">
					<Image
						src="/images/about.png"
						width={400}
						height={400}
						alt={'about'}
					/>
				</div>
			</div>
		</>
	);
};

export default About;
