import Image from "next/image";
import React from "react";
import Head from "next/head";
import Button, { BUTTON_STYLES } from "@/src/components/Button";
import { useState } from "react";

const About = () => {
  const foreground = "/images/foreground.png";
  const background = "/images/background.png";
  const arrow = "/images/arrow.svg";
  const [over, setOver] = useState(false);
  return (
    <>
      <Head>
        <title>Yoon Kim | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div className="flex md:flex-row flex-col items-center justify-center py-10">
        <div className="md:w-1/2 flex flex-col gap-5 px-3">
          <h2 className="font-bold tracking-tight text-4xl text-yellow">
            Annyeonghaseyo! 👋
          </h2>
          <div className="text-black text-md">
            <p className="pb-3">
              I’m Yoon (a.k.a. yoonthecoder), a frontend developer based in
              Vancouver, BC. I may have started my journey in Education, but I
              quickly discovered that my true passions lay in the world of tech.
              So, I taught myself to code and now I&apos;m living my dream as a
              developer! With a keen interest in both design and coding, I love
              getting creative with my work and always strive to create websites
              and applications that are not only functional, but also visually
              stunning.
            </p>
            <p className="pb-3">
              I also love to share my knowledge and experiences with others in
              the developer community. I recently started to create informative
              content on various platforms, so that other developers can learn
              from my tips and tricks and stay motivated with some inspirational
              quotes.
            </p>{" "}
            <p>
              When I&apos;m not in front of my laptop, you can find me on the
              mountains hitting the slops and recharging in nature!
            </p>{" "}
          </div>
          <div className="flex gap-3">
            <Button
              style={BUTTON_STYLES.UNDERLINE}
              text="View my resume ↗"
              buttonOnClick={() =>
                window.open("https://read.cv/yoonthecoder", "_target")
              }
            />
            <Button
              style={BUTTON_STYLES.UNDERLINE}
              text="Email me ↗"
              buttonOnClick={() =>
                (window.location.href = "mailto:imyoonkim@gmail.com")
              }
            />
          </div>
        </div>
        <div className="md:w-1/2 flex flex-col items-center justify-center">
          <Image
            src={over ? background : foreground}
            width={350}
            height={400}
            alt="headshot"
            className="cursor-pointer"
            onMouseOver={() => setOver(true)}
            onMouseOut={() => setOver(false)}
          />
          <div className="flex">
            {" "}
            <div className="text-yellow mt-10 mr-2">
              {over ? "thanks for coming by 💛" : "hover over me for a 🎁"}
            </div>
            <Image src={arrow} width={60} height={50} alt="arrow" />
          </div>
        </div>
      </div>
    </>
  );
};

export default About;
