import Head from 'next/head'
import { Figtree } from '@next/font/google'

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Yoon Kim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${figtree.variable} font-sans`}>
       <h1 className='text-yellow'>Yoon Kim</h1>
      </main>
    </>
  )
}
