import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import WorkSection from '@/src/components/WorkSection';
import ReviewSection from '@/src/components/ReviewSection';
import { BUTTON_STYLES } from '@/src/components/Button';
import Button from '@/src/components/Button';

export default function Home() {
	const heroImg = '/images/hero-img.svg';
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Yoon Kim | Front End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/favicon.ico" />
			</Head>

			<div className="w-full">
				<div className="flex md:flex-row flex-col">
					<div className="md:w-1/2 flex flex-col justify-center items-center md:items-start gap-4">
						<h1 className="uppercase text-6xl md:text-7xl text-center md:text-left">
							{' '}
							<div className="font-drukwide text-yellow">Yoon</div>
							<div className="font-drukwide">Kim</div>
						</h1>
						<h2 className="font-drukwide leading-tight uppercase text-center md:text-left text-black dark:text-lightgray">
							A frontend developer <br />
							who loves to{' '}
							<div
								className="container bg-yellow absolute z-10"
								style={{
									top: '40%',
									left: '50%',
								}}
							>
								<div className="slot pespective"></div>
							</div>
							<button className="code font-source lowercase text-3xl font-light relative">
								<mark
									className="bg-yellow/40 dark:bg-yellow/70 inline-block pb-3 dark:text-lightgray"
									style={{ lineHeight: '0rem' }}
								>
									code
								</mark>
							</button>{' '}
							and{' '}
							<button
								className="design lowercase text-3xl"
								onClick={() => {
									console.log('design clicked');
								}}
							>
								<mark
									className="bg-yellow/40 dark:bg-yellow/70 inline-block pb-3 font-felidae dark:text-lightgray"
									style={{ lineHeight: '0rem' }}
								>
									design.
								</mark>
							</button>
						</h2>

						<Button
							text={`Get to know more! →`}
							style={BUTTON_STYLES.UNDERLINE}
							buttonOnClick={() => router.push('/about')}
						/>
					</div>

					<div className="leading-6 md:justify-center md:w-1/2">
						<Image src={heroImg} width={500} height={500} alt="hero-img" />
					</div>
				</div>
				<div className="flex flex-col gap-5">
					<WorkSection />
					<ReviewSection />
				</div>
			</div>
		</>
	);
}
