import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import WorkSection from '@/src/components/WorkSection';
import ReviewSection from '@/src/components/ReviewSection';
import { BUTTON_STYLES } from '@/src/components/Button';
import Button from '@/src/components/Button';
import { ArrowRightIcon } from '@heroicons/react/24/solid';

export default function Home() {
	const heroImg = '/images/hero-img.svg';
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Yoon Kim | Front End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/favicon.ico" />
			</Head>

			<div className="md:max-w-7xl mx-auto flex items-center justify-center">
				<div>
					<h1 className="uppercase font-extrabold tracking-tighter text-6xl md:text-7xl text-center md:text-left text-yellow">
						Yoon Kim
					</h1>
					<h2 className="font-semibold text-black">
						A frontend developer who loves to code and design
					</h2>
				</div>
				<div>
					<div className="leading-6">
						<Image src={heroImg} width={500} height={500} alt="hero-img" />
					</div>
				</div>

				{/* <WorkSection />
				<ReviewSection /> */}
			</div>
		</>
	);
}
